services:
  nestar-next:
    container_name: petpalace-next
    restart: always
    image: node:20.10.0
    ports:
      - 4000:3000
    environment:
      - PORT=3000=value
    volumes:
      - .:/usr/src/next-palace
    working_dir: /usr/src/next-palace
    networks:
      - client-network

    # FOR PRODUCTION
    command: bash -c "yarn && yarn run build && yarn run start"

networks:
  monorepo-network:
    driver: bridge
